/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in typical projects and is kept in source
// here because the repository is being bootstrapped from an empty state.
